# ---------------------------------------------------------------
# Theme Core Configuration
# ---------------------------------------------------------------

# Schemes
# scheme: Muse
# scheme: Mist
# scheme: Pisces
scheme: Gemini

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  #categories: /categories/ || fa fa-th
  #archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

menu_settings:
  icons: true
  badges: true

# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------

sidebar:
  # Sidebar Position.
  position: left
  # Manual define the sidebar width. If commented, will be default for:
  # Muse | Mist: 320
  # Pisces | Gemini: 240
  # width: 300
  # Sidebar Display (only for Muse | Mist), available:
  #  - post    : expand on posts automatically. Default.
  #  - always  : expand for all pages automatically.
  #  - hide    : collapse on all pages automatically.
  #  - remove  : totally remove sidebar including sidebar toggle.
  display: remove
  # Sidebar padding in pixels.
  padding: 18
  # Sidebar offset from top menubar in pixels (only for Pisces | Gemini).
  offset: 12

avatar:
  # Replace the default image and set the url here.
  # url: /images/avatar.gif
  # If true, the avatar will be displayed in circle.
  rounded: true
  # If true, the avatar will be rotated with the cursor.
  rotated: false

social:
  GitHub: https://github.com/jf652366 || fab fa-github
  #E-Mail: mailto:yourname@gmail.com || fa fa-envelope
  #Twitter: https://twitter.com/yourname || fab fa-twitter

social_icons:
  enable: true
  icons_only: false
  transition: false

# ---------------------------------------------------------------
# Post Settings
# ---------------------------------------------------------------

# Automatically excerpt description in homepage as preamble text.
excerpt_description: true

# Read more button
# If true, the read more button will be displayed in excerpt section.
read_more_btn: true

# Post meta display settings
post_meta:
  item_text: true
  created_at: true
  updated_at: true
  categories: true

# ---------------------------------------------------------------
# Misc Theme Settings
# ---------------------------------------------------------------

# Code Highlight theme
codeblock:
  # Available values: normal | night | night eighties | night blue | night bright | solarized | solarized dark | galactic
  highlight_theme: normal
  # Add copy button on codeblock
  copy_btn: true
  # Show code block style
  style: mac

# Back to top in the sidebar.
back2top:
  enable: true
  # Back to top in sidebar.
  sidebar: false
  # Scroll percent label in b2t button.
  scrollpercent: true

# Reading progress bar
reading_progress:
  enable: true
  position: top
  color: "#37c6c0"
  height: 3px

# ---------------------------------------------------------------
# Footer Settings
# ---------------------------------------------------------------

footer:
  # Powered by Hexo & NexT
  powered: false
  # Copyright info
  copyright: false
